# Google Cloud Build configuration
steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-agent-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-agent-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    id: 'build-backend'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-agent-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-agent-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/resume-agent-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/resume-agent-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'resume-agent-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/resume-agent-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'FLASK_ENV=production'
      - '--set-secrets'
      - 'HUGGINGFACE_API_KEY=HUGGINGFACE_API_KEY:latest'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'resume-agent-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/resume-agent-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-backend']

images:
  - 'gcr.io/$PROJECT_ID/resume-agent-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/resume-agent-backend:latest'
  - 'gcr.io/$PROJECT_ID/resume-agent-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/resume-agent-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
